/**
 * @file api/creators-data.js
 * Comprehensive dataset for Cloutify / Influship MCP Intelligence
 */

export const INITIAL_CREATORS = [
  {
    id: 'kol-cheryl-tan',
    name: 'Cheryl Tan',
    handle: '@cheryl_dating_sg',
    verified: true,
    platform: 'instagram',
    tag: 'TOP MATCH',
    tagVariant: 'tertiary',
    shortlisted: true,
    score: 94,
    scoreBreakdown: {
      reach: 92,
      sentiment: 96,
      conversion: 94,
      algorithmConfidence: '94%',
    },
    category: 'Dating & Romance',
    subCategories: ['Modern Romance', 'Lifestyle SG', 'Relationship Wellness'],
    location: 'Singapore',
    localAudiencePct: 84,
    followers: 384000,
    followersDisplay: '384K',
    engagementRate: 4.8,
    engagementRateDisplay: '4.8%',
    avgImpressions: 42500,
    avgImpressionsDisplay: '42.5K',
    avgEngagement: 1800,
    avgEngagementDisplay: '1.8K',
    timeOnTop: '18 hrs',
    statusText: 'Peak Time on Top: 18 hrs',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAHbXcgJDGD_NNAFEEP1EvgRMXpItll2LxrgiwIdD6z9978o6La2gTwUNP8BCGOnj91r5Y01_EjPmHUXWEvmI2ZcTmjw1wOxkqYHNQeyXS1zXl9JMoIuI5bBR-SESXICdWR_4_y2q35797_GJEoisK3yAj-RPat7NLm70ikpbfu6MYKRnxsEV2wCWwHeY6D8aQ_08l6Nc8rL5p2BQ_0v_SXR9W6JcqIzHPBy2wuhY7se6YrimkDFdk-',
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    bio: 'Singapore dating columnist & lifestyle content creator. Host of "Table for Two SG" podcast exploring modern millennial dating, courtship etiquette, and cafe spots in the Lion City.',
    detailedBio: 'Cheryl Tan is one of Singapore’s most recognizable dating and relationship commentators. Over 6 years of consistent editorial and video storytelling, her candid takes on dating culture, marriage prep, and urban relationships have garnered a loyal local following with an exceptional 84% Singapore resident reach.',
    email: 'mgmt@cheryltan.media',
    agency: 'Lumen Talent Collective',
    languages: ['English', 'Mandarin'],
    pricingRange: '$2,800 - $4,200 / Reel',
    audienceQualityScore: 94,
    authenticityScore: 91,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    demographics: {
      gender: { female: 68, male: 32 },
      ageGroups: [
        { label: '18-24', pct: 28 },
        { label: '25-34', pct: 54 },
        { label: '35-44', pct: 14 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 84 },
        { country: 'Malaysia', pct: 9 },
        { country: 'Indonesia', pct: 4 },
        { country: 'Other', pct: 3 },
      ],
      topInterests: ['Dating & Relationships', 'Singapore Cafes & Bars', 'Boutique Fashion', 'Personal Wellness'],
    },
    mcpAudit: {
      decision: 'STRONG RECOMMENDATION',
      matchReason: 'Audience alignment in Singapore 25-34 age bracket is in the 99th percentile. Content transcript analysis shows consistent high positive sentiment (+0.84) on lifestyle brand integrations.',
      brandSafetyScore: 98,
      commercialIntentScore: 91,
      recommendationRank: 1,
    },
    recentProjects: [
      {
        id: 'proj-1',
        brand: 'Love, Bonito',
        brandLogo: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=120&q=80',
        title: 'Valentine’s Date Night Capsule Collection',
        campaignType: 'Sponsored Reel + 3x Stories',
        date: 'Feb 2026',
        thumbnail: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80',
        impressions: '68.4K',
        reach: '54.2K',
        engagementRate: '5.6%',
        saves: 1420,
        shares: 890,
        roiScore: 96,
        summary: 'Story-driven Reel comparing outfit dilemmas for 1st vs 5th dates. Achieved 210% of target brand link clicks in bio.',
      },
      {
        id: 'proj-2',
        brand: 'Tinder SG',
        brandLogo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&q=80',
        title: 'Single in the City: Honest First Dates',
        campaignType: 'Multi-part Reel Series',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80',
        impressions: '94.2K',
        reach: '78.0K',
        engagementRate: '6.1%',
        saves: 2150,
        shares: 1640,
        roiScore: 98,
        summary: 'Street interviews in Telok Ayer examining green flags and dealbreakers in Singapore dating scenes.',
      },
      {
        id: 'proj-3',
        brand: 'Sephora Southeast Asia',
        brandLogo: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=120&q=80',
        title: '10-Minute Sunset Glow Date Night Routine',
        campaignType: 'IG Carousel & GRWM Reel',
        date: 'Dec 2025',
        thumbnail: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=600&q=80',
        impressions: '51.8K',
        reach: '43.1K',
        engagementRate: '4.9%',
        saves: 1840,
        shares: 620,
        roiScore: 91,
        summary: 'Step-by-step beauty routine featuring gentle humidity-proof foundations tested in Singapore climate.',
      },
    ],
    recentPosts: [
      {
        id: 'post-1',
        type: 'Reel',
        caption: '5 unspoken rules of 1st dates in Singapore cafes vs bars ☕️🍷 Which one do you always check first?',
        likes: '3,840',
        comments: '184',
        views: '48.2K',
        postedAt: '1 day ago',
        thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=400&q=80',
      },
      {
        id: 'post-2',
        type: 'Carousel',
        caption: 'Late night supper spots in Tanjong Pagar that won’t break the bank when the conversation is too good to leave.',
        likes: '2,920',
        comments: '96',
        views: '34.5K',
        postedAt: '4 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=400&q=80',
      },
      {
        id: 'post-3',
        type: 'Reel',
        caption: 'When you both pretend you’re okay with split bills on the 3rd date 😅 (Sound on)',
        likes: '4,110',
        comments: '230',
        views: '56.1K',
        postedAt: '1 week ago',
        thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-marcus-sarah',
    name: 'Marcus & Sarah',
    handle: '@sg_couples_guide',
    verified: true,
    platform: 'tiktok',
    tag: 'Organic 98%',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 88,
    scoreBreakdown: {
      reach: 86,
      sentiment: 92,
      conversion: 88,
      algorithmConfidence: '88%',
    },
    category: 'Relationship Advice',
    subCategories: ['Couple Vlogs • SG', 'Home & BTO Living', 'Travel Escapes'],
    location: 'Singapore',
    localAudiencePct: 81,
    followers: 215000,
    followersDisplay: '215K',
    engagementRate: 5.2,
    engagementRateDisplay: '5.2%',
    avgImpressions: 31200,
    avgImpressionsDisplay: '31.2K',
    avgEngagement: 2100,
    avgEngagementDisplay: '2.1K',
    timeOnTop: '3 hrs ago',
    statusText: 'Last Post: 3 hrs ago',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9XwquoWlxWZaA2r48yp75OVdhNmI8-QLRro067MBhcY0Oia0h8Tk5lQ25J16_VS2ap1DX0aOep3j9niXqYcs3ixmrctUWI03EgWr_1Iaq_oBVs6gK4hV0NtyYdZqbaKBj-DmVWMfgYYibaJJ-SmUTj3fceZ1X3ur8VeXP-Ts1RpVQ30WI6fs1fb9hfSmFLDhW1SWRaphQaLrXP6qnyrbzN-liEq1vg9RmnKYrVyoldZXLtEKoIm02',
    coverImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80',
    bio: 'Singapore’s favorite candid couple sharing real talk on marriage, BTO renovations, budgeting together, and low-key date itineraries across Southeast Asia.',
    detailedBio: 'Marcus (software engineer) & Sarah (interior designer) turned their weekend dating vlogs into Singapore’s top couple lifestyle community. Known for zero-filter financial transparency, relationship conflict resolution tips, and honest home appliance tests.',
    email: 'partnerships@marcusandsarah.sg',
    agency: 'Independent',
    languages: ['English', 'Singlish'],
    pricingRange: '$2,200 - $3,400 / Video',
    audienceQualityScore: 89,
    authenticityScore: 98,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    demographics: {
      gender: { female: 58, male: 42 },
      ageGroups: [
        { label: '18-24', pct: 20 },
        { label: '25-34', pct: 62 },
        { label: '35-44', pct: 15 },
        { label: '45+', pct: 3 },
      ],
      geography: [
        { country: 'Singapore', pct: 81 },
        { country: 'Malaysia', pct: 12 },
        { country: 'Australia', pct: 4 },
        { country: 'Other', pct: 3 },
      ],
      topInterests: ['BTO Renovation & Home', 'Couple Financial Planning', 'Weekend Trips', 'Food Reviews'],
    },
    mcpAudit: {
      decision: 'STRONG RECOMMENDATION',
      matchReason: 'Unusually high organic retention score (98%). Comment section demonstrates genuine purchase intent for home goods and joint lifestyle experiences.',
      brandSafetyScore: 99,
      commercialIntentScore: 89,
      recommendationRank: 2,
    },
    recentProjects: [
      {
        id: 'proj-4',
        brand: 'Dyson Home Singapore',
        brandLogo: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=120&q=80',
        title: 'BTO Cleaning Routines: Who Does What?',
        campaignType: 'TikTok Video + Instagram Reel',
        date: 'Feb 2026',
        thumbnail: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
        impressions: '82.0K',
        reach: '67.5K',
        engagementRate: '5.9%',
        saves: 1890,
        shares: 1120,
        roiScore: 94,
        summary: 'Humorous couple chore division trial featuring Dyson V12 cordless vacuum with real living room chaos test.',
      },
      {
        id: 'proj-5',
        brand: 'Klook SG',
        brandLogo: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=120&q=80',
        title: '48hr Desaru Weekend Getaway under $300',
        campaignType: 'Vlog + Carousel Guide',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        impressions: '91.4K',
        reach: '74.2K',
        engagementRate: '6.4%',
        saves: 3410,
        shares: 2200,
        roiScore: 97,
        summary: 'Budget breakdown and hotel booking voucher push. Drove over 420 direct affiliate checkouts.',
      },
    ],
    recentPosts: [
      {
        id: 'post-4',
        type: 'TikTok',
        caption: 'The awkward conversation when one person wants aircon at 22C and the other at 26C 🥶',
        likes: '4,200',
        comments: '340',
        views: '62.0K',
        postedAt: '3 hours ago',
        thumbnail: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=400&q=80',
      },
      {
        id: 'post-5',
        type: 'Reel',
        caption: '5 things we cut from our 4-room BTO reno budget that saved us $14,000 without regret.',
        likes: '5,890',
        comments: '412',
        views: '88.1K',
        postedAt: '3 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-daniel-heng',
    name: 'Daniel Heng',
    handle: '@dan_singaporean_dates',
    verified: false,
    platform: 'instagram',
    tag: 'Trending Up 🚀',
    tagVariant: 'secondary-fixed',
    shortlisted: false,
    score: 82,
    scoreBreakdown: {
      reach: 84,
      sentiment: 81,
      conversion: 80,
      algorithmConfidence: '82%',
    },
    category: 'Speed Dating & Nightlife',
    subCategories: ['Nightlife SG', 'Speakeasies & Bars', 'Urban Men Style'],
    location: 'Singapore',
    localAudiencePct: 79,
    followers: 145000,
    followersDisplay: '145K',
    engagementRate: 3.9,
    engagementRateDisplay: '3.9%',
    avgImpressions: 19400,
    avgImpressionsDisplay: '19.4K',
    avgEngagement: 750,
    avgEngagementDisplay: '750',
    timeOnTop: '9.5 hrs',
    statusText: 'Time on Top: 9.5 hrs',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzUg-fdZoL1ahvimNJ4yab9ZP9AtGYbyvEqXHfMmZIhuqFypZJRt4uMepA7R5JWBwS_FAz8tQtGhsyOfHCv1ew6Z4FuCLw4s2aVg2AGe6UJpWXwDiKRWv9saz2sCpu-cfNsyA89qBXnyCsrGWfL5lH8DvfgWkJ2prK7A9knF68iwniancMMCXPn3OtaeIvrC6l2xLpgMz9qw_xpZkAnsgud32jC3FsQpzb3WFP6-vEw1UwKLdY_1xu',
    coverImage: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
    bio: 'Curator of hidden date spots, speakeasy cocktails, and Friday night speed dating mixers across Clarke Quay, Telok Ayer, and Keong Saik.',
    detailedBio: 'Daniel produces sharp, cinematic micro-reviews of Singapore nightlife and high-energy singles mixers. He organizes monthly curated speed dating events with 100+ attendees in Marina Bay venues.',
    email: 'dan@singaporeandates.com',
    agency: 'Waveform Media',
    languages: ['English'],
    pricingRange: '$1,600 - $2,500 / Reel',
    audienceQualityScore: 84,
    authenticityScore: 86,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    demographics: {
      gender: { female: 46, male: 54 },
      ageGroups: [
        { label: '18-24', pct: 24 },
        { label: '25-34', pct: 52 },
        { label: '35-44', pct: 18 },
        { label: '45+', pct: 6 },
      ],
      geography: [
        { country: 'Singapore', pct: 79 },
        { country: 'Malaysia', pct: 11 },
        { country: 'Hong Kong', pct: 5 },
        { country: 'Other', pct: 5 },
      ],
      topInterests: ['Cocktail Bars & Speakeasies', 'Nightlife', 'Singles Events', 'Men Grooming'],
    },
    mcpAudit: {
      decision: 'GOOD MATCH',
      matchReason: 'Dominant footprint in Singapore after-dark and cocktail culture. Rapid MoM velocity in comments requesting venue booking codes.',
      brandSafetyScore: 92,
      commercialIntentScore: 85,
      recommendationRank: 3,
    },
    recentProjects: [
      {
        id: 'proj-6',
        brand: 'Marina Bay Sands Hospitality',
        brandLogo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=120&q=80',
        title: 'Secret Rooftop Date Night Series',
        campaignType: 'Cinematic Reel + Event Host',
        date: 'Feb 2026',
        thumbnail: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=600&q=80',
        impressions: '42.1K',
        reach: '36.8K',
        engagementRate: '4.2%',
        saves: 1420,
        shares: 980,
        roiScore: 88,
        summary: 'Exclusive access walk-through of twilight tasting menus and mixology bar seating.',
      },
    ],
    recentPosts: [
      {
        id: 'post-6',
        type: 'Reel',
        caption: '3 hidden cocktail doors in Chinatown you’ve walked past 100 times without noticing 🍸',
        likes: '1,890',
        comments: '124',
        views: '26.4K',
        postedAt: '9.5 hours ago',
        thumbnail: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-jade-lin',
    name: 'Jade Lin',
    handle: '@jadelin_sg',
    verified: false,
    platform: 'youtube',
    tag: 'Rising Creator',
    tagVariant: 'tertiary-fixed',
    shortlisted: false,
    score: 79,
    scoreBreakdown: {
      reach: 78,
      sentiment: 85,
      conversion: 74,
      algorithmConfidence: '79%',
    },
    category: 'Dating Humor & Podcasts',
    subCategories: ['Gen Z Singapore', 'College Stories', 'Comedy Sketches'],
    location: 'Singapore',
    localAudiencePct: 88,
    followers: 98000,
    followersDisplay: '98K',
    engagementRate: 6.1,
    engagementRateDisplay: '6.1%',
    avgImpressions: 15800,
    avgImpressionsDisplay: '15.8K',
    avgEngagement: 960,
    avgEngagementDisplay: '960',
    timeOnTop: '+14.2% MoM',
    statusText: 'Growth: +14.2% MoM',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDoFxEapKNNWgHjBf_KnYGj8cNuo-RvL43OdDlGRMRTiqh9DaVsMqKsxzAsrRpCudxPhDjooX9B4GeYgbhgOD6EWISOt9CBuU7-S8PWGOOZQ8hRT-s-H2ihEYbH1D24bWicXnN2PyxUVe7ML38DmmDMSTwqA6YPniOcb1Ywcsfo4IjfpLnrJHf_XTwMYcD2Vrb0Ixz_jyEg8AJ3pYDC3_9ThAkcAXN5Sm_t4R_99dGuUxnn6TUdO8Kn',
    coverImage: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&w=1200&q=80',
    bio: 'Gen Z podcast creator dissecting dating red flags, ghosting culture in NUS/NTU, and millennial vs Gen Z texting habits. High-energy, unfiltered, hilarious.',
    detailedBio: 'Jade Lin is an emerging digital creator who built a cult following across YouTube Shorts and TikTok with her relatable parody reenactments of contemporary dating scenarios in Singapore.',
    email: 'jadelin.mgmt@gmail.com',
    agency: 'Direct Creator',
    languages: ['English', 'Singlish'],
    pricingRange: '$1,200 - $1,800 / Short',
    audienceQualityScore: 88,
    authenticityScore: 94,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    demographics: {
      gender: { female: 72, male: 28 },
      ageGroups: [
        { label: '18-24', pct: 64 },
        { label: '25-34', pct: 28 },
        { label: '35-44', pct: 6 },
        { label: '45+', pct: 2 },
      ],
      geography: [
        { country: 'Singapore', pct: 88 },
        { country: 'Malaysia', pct: 8 },
        { country: 'Other', pct: 4 },
      ],
      topInterests: ['Comedy & Memes', 'University Life', 'Dating Stories', 'Gen Z Streetwear'],
    },
    mcpAudit: {
      decision: 'RISING POTENTIAL',
      matchReason: 'Top tier organic engagement rate (6.1%) for under 100K follower bracket. Ideal for campaigns seeking authentic youth resonance.',
      brandSafetyScore: 95,
      commercialIntentScore: 78,
      recommendationRank: 4,
    },
    recentProjects: [
      {
        id: 'proj-7',
        brand: 'Bumble Southeast Asia',
        brandLogo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
        title: 'Bumble Opening Line Roast Challenge',
        campaignType: 'YouTube Shorts + Live Stream Q&A',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
        impressions: '64.0K',
        reach: '51.2K',
        engagementRate: '7.8%',
        saves: 1670,
        shares: 2400,
        roiScore: 93,
        summary: 'Invited campus students to share their cringiest opening messages with witty live feedback.',
      },
    ],
    recentPosts: [
      {
        id: 'post-7',
        type: 'Short',
        caption: 'He said he’s "not looking for anything serious right now" during dinner at Marina Bay Sands 💀',
        likes: '3,100',
        comments: '290',
        views: '44.8K',
        postedAt: '2 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-rachel-kenneth',
    name: 'Rachel & Kenneth',
    handle: '@sgfood_romance',
    verified: true,
    platform: 'instagram',
    tag: 'High Intent',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 85,
    scoreBreakdown: {
      reach: 83,
      sentiment: 88,
      conversion: 86,
      algorithmConfidence: '85%',
    },
    category: 'Dating & Romance',
    subCategories: ['Couple Dining', 'Michelin Date Nights', 'Foodie SG'],
    location: 'Singapore',
    localAudiencePct: 86,
    followers: 182000,
    followersDisplay: '182K',
    engagementRate: 4.4,
    engagementRateDisplay: '4.4%',
    avgImpressions: 27500,
    avgImpressionsDisplay: '27.5K',
    avgEngagement: 1210,
    avgEngagementDisplay: '1.2K',
    timeOnTop: '12 hrs',
    statusText: 'Peak Time on Top: 12 hrs',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    bio: 'Food-first couples exploring anniversary specials, romantic hidden trattorias, and weekend cafe dates in Singapore and Johor Bahru.',
    detailedBio: 'Rachel & Kenneth specialize in culinary romance. Their curated date-night itineraries combine aesthetic food cinematography with honest feedback on pricing, ambiance, and acoustic levels for intimate conversations.',
    email: 'collab@sgfoodromance.com',
    agency: 'Lumen Talent Collective',
    languages: ['English', 'Mandarin'],
    pricingRange: '$2,000 - $3,000 / Collab',
    audienceQualityScore: 90,
    authenticityScore: 92,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    demographics: {
      gender: { female: 62, male: 38 },
      ageGroups: [
        { label: '18-24', pct: 22 },
        { label: '25-34', pct: 58 },
        { label: '35-44', pct: 16 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 86 },
        { country: 'Malaysia', pct: 10 },
        { country: 'Other', pct: 4 },
      ],
      topInterests: ['Fine Dining', 'Date Night Guides', 'Weekend Getaways', 'Cocktail Pairings'],
    },
    mcpAudit: {
      decision: 'GOOD MATCH',
      matchReason: 'Exceptional save rate for restaurant lists. Highly converted audience demographic with above-average disposable income.',
      brandSafetyScore: 97,
      commercialIntentScore: 88,
      recommendationRank: 5,
    },
    recentProjects: [
      {
        id: 'proj-8',
        brand: 'Chope Singapore',
        brandLogo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=120&q=80',
        title: 'Top 10 Romantic Restaurants for Anniversaries',
        campaignType: 'Carousel Guide + Voucher Drop',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=600&q=80',
        impressions: '52.4K',
        reach: '44.1K',
        engagementRate: '5.1%',
        saves: 2840,
        shares: 1950,
        roiScore: 95,
        summary: 'High-performing reservation campaign resulting in 820 table bookings.',
      },
    ],
    recentPosts: [
      {
        id: 'post-8',
        type: 'Reel',
        caption: 'The most romantic garden restaurant in Dempsey where candlelight does all the work ✨',
        likes: '2,400',
        comments: '115',
        views: '38.0K',
        postedAt: '2 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-bryan-tan',
    name: 'Bryan Tan',
    handle: '@bryan_sg_fit',
    verified: false,
    platform: 'instagram',
    tag: 'Athletic Vibe',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 80,
    scoreBreakdown: {
      reach: 82,
      sentiment: 78,
      conversion: 80,
      algorithmConfidence: '80%',
    },
    category: 'Lifestyle SG',
    subCategories: ['Active Dating', 'Hyrox & Running Clubs', 'Athleisure'],
    location: 'Singapore',
    localAudiencePct: 76,
    followers: 120000,
    followersDisplay: '120K',
    engagementRate: 4.1,
    engagementRateDisplay: '4.1%',
    avgImpressions: 17200,
    avgImpressionsDisplay: '17.2K',
    avgEngagement: 820,
    avgEngagementDisplay: '820',
    timeOnTop: '6.2 hrs',
    statusText: 'Peak Time on Top: 6.2 hrs',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
    bio: 'Founder of East Coast Sunrise Run Club. Championing active dates, bouldering meetups, and fitness romance over late drinks.',
    detailedBio: 'Bryan has spearheaded Singapore’s fast-growing run club dating phenomenon, organizing Sunday 5K jogs followed by iced flat whites where over 200 singles connect weekly.',
    email: 'bryan@sgfitrun.com',
    agency: 'Independent',
    languages: ['English'],
    pricingRange: '$1,500 - $2,200 / Post',
    audienceQualityScore: 83,
    authenticityScore: 89,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    demographics: {
      gender: { female: 52, male: 48 },
      ageGroups: [
        { label: '18-24', pct: 30 },
        { label: '25-34', pct: 54 },
        { label: '35-44', pct: 12 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 76 },
        { country: 'Malaysia', pct: 14 },
        { country: 'Other', pct: 10 },
      ],
      topInterests: ['Running Clubs', 'Athleisure', 'Active Dating', 'Sports Nutrition'],
    },
    mcpAudit: {
      decision: 'GOOD MATCH',
      matchReason: 'Unique high-engagement community niche around active social wellness and singles run clubs in Singapore.',
      brandSafetyScore: 98,
      commercialIntentScore: 82,
      recommendationRank: 6,
    },
    recentProjects: [
      {
        id: 'proj-9',
        brand: 'Lululemon Singapore',
        brandLogo: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=120&q=80',
        title: 'Run & Coffee Singles Social Series',
        campaignType: 'Community Event + Reel',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=600&q=80',
        impressions: '38.0K',
        reach: '32.1K',
        engagementRate: '5.2%',
        saves: 1100,
        shares: 850,
        roiScore: 90,
        summary: 'Co-branded sunrise community run ending with complimentary matcha lattes and meet-and-greets.',
      },
    ],
    recentPosts: [
      {
        id: 'post-9',
        type: 'Reel',
        caption: 'Why Sunday morning run clubs became Singapore’s new speed dating scene 👟☕️',
        likes: '2,150',
        comments: '160',
        views: '31.2K',
        postedAt: '3 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1483721074577-8383e634336c?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
];
