/**
 * @file api/creators-data.js
 * Comprehensive dataset for Cloutify / Influship MCP Intelligence
 */

export const INITIAL_CREATORS = [
  {
    id: 'kol-cheryl-tan',
    name: 'Cheryl Tan',
    handle: '@cheryl_dating_sg',
    verified: true,
    platform: 'instagram',
    tag: 'TOP MATCH',
    tagVariant: 'tertiary',
    shortlisted: true,
    score: 94,
    scoreBreakdown: {
      reach: 92,
      sentiment: 96,
      conversion: 94,
      algorithmConfidence: '94%',
    },
    category: 'Dating & Romance',
    subCategories: ['Modern Romance', 'Lifestyle SG', 'Relationship Wellness'],
    location: 'Singapore',
    localAudiencePct: 84,
    followers: 384000,
    followersDisplay: '384K',
    engagementRate: 4.8,
    engagementRateDisplay: '4.8%',
    avgImpressions: 42500,
    avgImpressionsDisplay: '42.5K',
    avgEngagement: 1800,
    avgEngagementDisplay: '1.8K',
    timeOnTop: '18 hrs',
    statusText: 'Peak Time on Top: 18 hrs',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAHbXcgJDGD_NNAFEEP1EvgRMXpItll2LxrgiwIdD6z9978o6La2gTwUNP8BCGOnj91r5Y01_EjPmHUXWEvmI2ZcTmjw1wOxkqYHNQeyXS1zXl9JMoIuI5bBR-SESXICdWR_4_y2q35797_GJEoisK3yAj-RPat7NLm70ikpbfu6MYKRnxsEV2wCWwHeY6D8aQ_08l6Nc8rL5p2BQ_0v_SXR9W6JcqIzHPBy2wuhY7se6YrimkDFdk-',
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    bio: 'Singapore dating columnist & lifestyle content creator. Host of "Table for Two SG" podcast exploring modern millennial dating, courtship etiquette, and cafe spots in the Lion City.',
    detailedBio: 'Cheryl Tan is one of Singapore’s most recognizable dating and relationship commentators. Over 6 years of consistent editorial and video storytelling, her candid takes on dating culture, marriage prep, and urban relationships have garnered a loyal local following with an exceptional 84% Singapore resident reach.',
    email: 'mgmt@cheryltan.media',
    agency: 'Lumen Talent Collective',
    languages: ['English', 'Mandarin'],
    pricingRange: '$2,800 - $4,200 / Reel',
    audienceQualityScore: 94,
    authenticityScore: 91,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    demographics: {
      gender: { female: 68, male: 32 },
      ageGroups: [
        { label: '18-24', pct: 28 },
        { label: '25-34', pct: 54 },
        { label: '35-44', pct: 14 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 84 },
        { country: 'Malaysia', pct: 9 },
        { country: 'Indonesia', pct: 4 },
        { country: 'Other', pct: 3 },
      ],
      topInterests: ['Dating & Relationships', 'Singapore Cafes & Bars', 'Boutique Fashion', 'Personal Wellness'],
    },
    mcpAudit: {
      decision: 'STRONG RECOMMENDATION',
      matchReason: 'Audience alignment in Singapore 25-34 age bracket is in the 99th percentile. Content transcript analysis shows consistent high positive sentiment (+0.84) on lifestyle brand integrations.',
      brandSafetyScore: 98,
      commercialIntentScore: 91,
      recommendationRank: 1,
    },
    recentProjects: [
      {
        id: 'proj-1',
        brand: 'Love, Bonito',
        brandLogo: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=120&q=80',
        title: 'Valentine’s Date Night Capsule Collection',
        campaignType: 'Sponsored Reel + 3x Stories',
        date: 'Feb 2026',
        thumbnail: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80',
        impressions: '68.4K',
        reach: '54.2K',
        engagementRate: '5.6%',
        saves: 1420,
        shares: 890,
        roiScore: 96,
        summary: 'Story-driven Reel comparing outfit dilemmas for 1st vs 5th dates. Achieved 210% of target brand link clicks in bio.',
      },
      {
        id: 'proj-2',
        brand: 'Tinder SG',
        brandLogo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&q=80',
        title: 'Single in the City: Honest First Dates',
        campaignType: 'Multi-part Reel Series',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80',
        impressions: '94.2K',
        reach: '78.0K',
        engagementRate: '6.1%',
        saves: 2150,
        shares: 1640,
        roiScore: 98,
        summary: 'Street interviews in Telok Ayer examining green flags and dealbreakers in Singapore dating scenes.',
      },
      {
        id: 'proj-3',
        brand: 'Sephora Southeast Asia',
        brandLogo: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=120&q=80',
        title: '10-Minute Sunset Glow Date Night Routine',
        campaignType: 'IG Carousel & GRWM Reel',
        date: 'Dec 2025',
        thumbnail: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=600&q=80',
        impressions: '51.8K',
        reach: '43.1K',
        engagementRate: '4.9%',
        saves: 1840,
        shares: 620,
        roiScore: 91,
        summary: 'Step-by-step beauty routine featuring gentle humidity-proof foundations tested in Singapore climate.',
      },
    ],
    recentPosts: [
      {
        id: 'post-1',
        type: 'Reel',
        caption: '5 unspoken rules of 1st dates in Singapore cafes vs bars ☕️🍷 Which one do you always check first?',
        likes: '3,840',
        comments: '184',
        views: '48.2K',
        postedAt: '1 day ago',
        thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=400&q=80',
      },
      {
        id: 'post-2',
        type: 'Carousel',
        caption: 'Late night supper spots in Tanjong Pagar that won’t break the bank when the conversation is too good to leave.',
        likes: '2,920',
        comments: '96',
        views: '34.5K',
        postedAt: '4 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=400&q=80',
      },
      {
        id: 'post-3',
        type: 'Reel',
        caption: 'When you both pretend you’re okay with split bills on the 3rd date 😅 (Sound on)',
        likes: '4,110',
        comments: '230',
        views: '56.1K',
        postedAt: '1 week ago',
        thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-marcus-sarah',
    name: 'Marcus & Sarah',
    handle: '@sg_couples_guide',
    verified: true,
    platform: 'tiktok',
    tag: 'Organic 98%',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 88,
    scoreBreakdown: {
      reach: 86,
      sentiment: 92,
      conversion: 88,
      algorithmConfidence: '88%',
    },
    category: 'Relationship Advice',
    subCategories: ['Couple Vlogs • SG', 'Home & BTO Living', 'Travel Escapes'],
    location: 'Singapore',
    localAudiencePct: 81,
    followers: 215000,
    followersDisplay: '215K',
    engagementRate: 5.2,
    engagementRateDisplay: '5.2%',
    avgImpressions: 31200,
    avgImpressionsDisplay: '31.2K',
    avgEngagement: 2100,
    avgEngagementDisplay: '2.1K',
    timeOnTop: '3 hrs ago',
    statusText: 'Last Post: 3 hrs ago',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9XwquoWlxWZaA2r48yp75OVdhNmI8-QLRro067MBhcY0Oia0h8Tk5lQ25J16_VS2ap1DX0aOep3j9niXqYcs3ixmrctUWI03EgWr_1Iaq_oBVs6gK4hV0NtyYdZqbaKBj-DmVWMfgYYibaJJ-SmUTj3fceZ1X3ur8VeXP-Ts1RpVQ30WI6fs1fb9hfSmFLDhW1SWRaphQaLrXP6qnyrbzN-liEq1vg9RmnKYrVyoldZXLtEKoIm02',
    coverImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80',
    bio: 'Singapore’s favorite candid couple sharing real talk on marriage, BTO renovations, budgeting together, and low-key date itineraries across Southeast Asia.',
    detailedBio: 'Marcus (software engineer) & Sarah (interior designer) turned their weekend dating vlogs into Singapore’s top couple lifestyle community. Known for zero-filter financial transparency, relationship conflict resolution tips, and honest home appliance tests.',
    email: 'partnerships@marcusandsarah.sg',
    agency: 'Independent',
    languages: ['English', 'Singlish'],
    pricingRange: '$2,200 - $3,400 / Video',
    audienceQualityScore: 89,
    authenticityScore: 98,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    demographics: {
      gender: { female: 58, male: 42 },
      ageGroups: [
        { label: '18-24', pct: 20 },
        { label: '25-34', pct: 62 },
        { label: '35-44', pct: 15 },
        { label: '45+', pct: 3 },
      ],
      geography: [
        { country: 'Singapore', pct: 81 },
        { country: 'Malaysia', pct: 12 },
        { country: 'Australia', pct: 4 },
        { country: 'Other', pct: 3 },
      ],
      topInterests: ['BTO Renovation & Home', 'Couple Financial Planning', 'Weekend Trips', 'Food Reviews'],
    },
    mcpAudit: {
      decision: 'STRONG RECOMMENDATION',
      matchReason: 'Unusually high organic retention score (98%). Comment section demonstrates genuine purchase intent for home goods and joint lifestyle experiences.',
      brandSafetyScore: 99,
      commercialIntentScore: 89,
      recommendationRank: 2,
    },
    recentProjects: [
      {
        id: 'proj-4',
        brand: 'Dyson Home Singapore',
        brandLogo: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=120&q=80',
        title: 'BTO Cleaning Routines: Who Does What?',
        campaignType: 'TikTok Video + Instagram Reel',
        date: 'Feb 2026',
        thumbnail: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
        impressions: '82.0K',
        reach: '67.5K',
        engagementRate: '5.9%',
        saves: 1890,
        shares: 1120,
        roiScore: 94,
        summary: 'Humorous couple chore division trial featuring Dyson V12 cordless vacuum with real living room chaos test.',
      },
      {
        id: 'proj-5',
        brand: 'Klook SG',
        brandLogo: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=120&q=80',
        title: '48hr Desaru Weekend Getaway under $300',
        campaignType: 'Vlog + Carousel Guide',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        impressions: '91.4K',
        reach: '74.2K',
        engagementRate: '6.4%',
        saves: 3410,
        shares: 2200,
        roiScore: 97,
        summary: 'Budget breakdown and hotel booking voucher push. Drove over 420 direct affiliate checkouts.',
      },
    ],
    recentPosts: [
      {
        id: 'post-4',
        type: 'TikTok',
        caption: 'The awkward conversation when one person wants aircon at 22C and the other at 26C 🥶',
        likes: '4,200',
        comments: '340',
        views: '62.0K',
        postedAt: '3 hours ago',
        thumbnail: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=400&q=80',
      },
      {
        id: 'post-5',
        type: 'Reel',
        caption: '5 things we cut from our 4-room BTO reno budget that saved us $14,000 without regret.',
        likes: '5,890',
        comments: '412',
        views: '88.1K',
        postedAt: '3 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-daniel-heng',
    name: 'Daniel Heng',
    handle: '@dan_singaporean_dates',
    verified: false,
    platform: 'instagram',
    tag: 'Trending Up 🚀',
    tagVariant: 'secondary-fixed',
    shortlisted: false,
    score: 82,
    scoreBreakdown: {
      reach: 84,
      sentiment: 81,
      conversion: 80,
      algorithmConfidence: '82%',
    },
    category: 'Speed Dating & Nightlife',
    subCategories: ['Nightlife SG', 'Speakeasies & Bars', 'Urban Men Style'],
    location: 'Singapore',
    localAudiencePct: 79,
    followers: 145000,
    followersDisplay: '145K',
    engagementRate: 3.9,
    engagementRateDisplay: '3.9%',
    avgImpressions: 19400,
    avgImpressionsDisplay: '19.4K',
    avgEngagement: 750,
    avgEngagementDisplay: '750',
    timeOnTop: '9.5 hrs',
    statusText: 'Time on Top: 9.5 hrs',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzUg-fdZoL1ahvimNJ4yab9ZP9AtGYbyvEqXHfMmZIhuqFypZJRt4uMepA7R5JWBwS_FAz8tQtGhsyOfHCv1ew6Z4FuCLw4s2aVg2AGe6UJpWXwDiKRWv9saz2sCpu-cfNsyA89qBXnyCsrGWfL5lH8DvfgWkJ2prK7A9knF68iwniancMMCXPn3OtaeIvrC6l2xLpgMz9qw_xpZkAnsgud32jC3FsQpzb3WFP6-vEw1UwKLdY_1xu',
    coverImage: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
    bio: 'Curator of hidden date spots, speakeasy cocktails, and Friday night speed dating mixers across Clarke Quay, Telok Ayer, and Keong Saik.',
    detailedBio: 'Daniel produces sharp, cinematic micro-reviews of Singapore nightlife and high-energy singles mixers. He organizes monthly curated speed dating events with 100+ attendees in Marina Bay venues.',
    email: 'dan@singaporeandates.com',
    agency: 'Waveform Media',
    languages: ['English'],
    pricingRange: '$1,600 - $2,500 / Reel',
    audienceQualityScore: 84,
    authenticityScore: 86,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    demographics: {
      gender: { female: 46, male: 54 },
      ageGroups: [
        { label: '18-24', pct: 24 },
        { label: '25-34', pct: 52 },
        { label: '35-44', pct: 18 },
        { label: '45+', pct: 6 },
      ],
      geography: [
        { country: 'Singapore', pct: 79 },
        { country: 'Malaysia', pct: 11 },
        { country: 'Hong Kong', pct: 5 },
        { country: 'Other', pct: 5 },
      ],
      topInterests: ['Cocktail Bars & Speakeasies', 'Nightlife', 'Singles Events', 'Men Grooming'],
    },
    mcpAudit: {
      decision: 'GOOD MATCH',
      matchReason: 'Dominant footprint in Singapore after-dark and cocktail culture. Rapid MoM velocity in comments requesting venue booking codes.',
      brandSafetyScore: 92,
      commercialIntentScore: 85,
      recommendationRank: 3,
    },
    recentProjects: [
      {
        id: 'proj-6',
        brand: 'Marina Bay Sands Hospitality',
        brandLogo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=120&q=80',
        title: 'Secret Rooftop Date Night Series',
        campaignType: 'Cinematic Reel + Event Host',
        date: 'Feb 2026',
        thumbnail: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=600&q=80',
        impressions: '42.1K',
        reach: '36.8K',
        engagementRate: '4.2%',
        saves: 1420,
        shares: 980,
        roiScore: 88,
        summary: 'Exclusive access walk-through of twilight tasting menus and mixology bar seating.',
      },
    ],
    recentPosts: [
      {
        id: 'post-6',
        type: 'Reel',
        caption: '3 hidden cocktail doors in Chinatown you’ve walked past 100 times without noticing 🍸',
        likes: '1,890',
        comments: '124',
        views: '26.4K',
        postedAt: '9.5 hours ago',
        thumbnail: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-jade-lin',
    name: 'Jade Lin',
    handle: '@jadelin_sg',
    verified: false,
    platform: 'youtube',
    tag: 'Rising Creator',
    tagVariant: 'tertiary-fixed',
    shortlisted: false,
    score: 79,
    scoreBreakdown: {
      reach: 78,
      sentiment: 85,
      conversion: 74,
      algorithmConfidence: '79%',
    },
    category: 'Dating Humor & Podcasts',
    subCategories: ['Gen Z Singapore', 'College Stories', 'Comedy Sketches'],
    location: 'Singapore',
    localAudiencePct: 88,
    followers: 98000,
    followersDisplay: '98K',
    engagementRate: 6.1,
    engagementRateDisplay: '6.1%',
    avgImpressions: 15800,
    avgImpressionsDisplay: '15.8K',
    avgEngagement: 960,
    avgEngagementDisplay: '960',
    timeOnTop: '+14.2% MoM',
    statusText: 'Growth: +14.2% MoM',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDoFxEapKNNWgHjBf_KnYGj8cNuo-RvL43OdDlGRMRTiqh9DaVsMqKsxzAsrRpCudxPhDjooX9B4GeYgbhgOD6EWISOt9CBuU7-S8PWGOOZQ8hRT-s-H2ihEYbH1D24bWicXnN2PyxUVe7ML38DmmDMSTwqA6YPniOcb1Ywcsfo4IjfpLnrJHf_XTwMYcD2Vrb0Ixz_jyEg8AJ3pYDC3_9ThAkcAXN5Sm_t4R_99dGuUxnn6TUdO8Kn',
    coverImage: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&w=1200&q=80',
    bio: 'Gen Z podcast creator dissecting dating red flags, ghosting culture in NUS/NTU, and millennial vs Gen Z texting habits. High-energy, unfiltered, hilarious.',
    detailedBio: 'Jade Lin is an emerging digital creator who built a cult following across YouTube Shorts and TikTok with her relatable parody reenactments of contemporary dating scenarios in Singapore.',
    email: 'jadelin.mgmt@gmail.com',
    agency: 'Direct Creator',
    languages: ['English', 'Singlish'],
    pricingRange: '$1,200 - $1,800 / Short',
    audienceQualityScore: 88,
    authenticityScore: 94,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    demographics: {
      gender: { female: 72, male: 28 },
      ageGroups: [
        { label: '18-24', pct: 64 },
        { label: '25-34', pct: 28 },
        { label: '35-44', pct: 6 },
        { label: '45+', pct: 2 },
      ],
      geography: [
        { country: 'Singapore', pct: 88 },
        { country: 'Malaysia', pct: 8 },
        { country: 'Other', pct: 4 },
      ],
      topInterests: ['Comedy & Memes', 'University Life', 'Dating Stories', 'Gen Z Streetwear'],
    },
    mcpAudit: {
      decision: 'RISING POTENTIAL',
      matchReason: 'Top tier organic engagement rate (6.1%) for under 100K follower bracket. Ideal for campaigns seeking authentic youth resonance.',
      brandSafetyScore: 95,
      commercialIntentScore: 78,
      recommendationRank: 4,
    },
    recentProjects: [
      {
        id: 'proj-7',
        brand: 'Bumble Southeast Asia',
        brandLogo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
        title: 'Bumble Opening Line Roast Challenge',
        campaignType: 'YouTube Shorts + Live Stream Q&A',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
        impressions: '64.0K',
        reach: '51.2K',
        engagementRate: '7.8%',
        saves: 1670,
        shares: 2400,
        roiScore: 93,
        summary: 'Invited campus students to share their cringiest opening messages with witty live feedback.',
      },
    ],
    recentPosts: [
      {
        id: 'post-7',
        type: 'Short',
        caption: 'He said he’s "not looking for anything serious right now" during dinner at Marina Bay Sands 💀',
        likes: '3,100',
        comments: '290',
        views: '44.8K',
        postedAt: '2 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-rachel-kenneth',
    name: 'Rachel & Kenneth',
    handle: '@sgfood_romance',
    verified: true,
    platform: 'instagram',
    tag: 'High Intent',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 85,
    scoreBreakdown: {
      reach: 83,
      sentiment: 88,
      conversion: 86,
      algorithmConfidence: '85%',
    },
    category: 'Dating & Romance',
    subCategories: ['Couple Dining', 'Michelin Date Nights', 'Foodie SG'],
    location: 'Singapore',
    localAudiencePct: 86,
    followers: 182000,
    followersDisplay: '182K',
    engagementRate: 4.4,
    engagementRateDisplay: '4.4%',
    avgImpressions: 27500,
    avgImpressionsDisplay: '27.5K',
    avgEngagement: 1210,
    avgEngagementDisplay: '1.2K',
    timeOnTop: '12 hrs',
    statusText: 'Peak Time on Top: 12 hrs',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    bio: 'Food-first couples exploring anniversary specials, romantic hidden trattorias, and weekend cafe dates in Singapore and Johor Bahru.',
    detailedBio: 'Rachel & Kenneth specialize in culinary romance. Their curated date-night itineraries combine aesthetic food cinematography with honest feedback on pricing, ambiance, and acoustic levels for intimate conversations.',
    email: 'collab@sgfoodromance.com',
    agency: 'Lumen Talent Collective',
    languages: ['English', 'Mandarin'],
    pricingRange: '$2,000 - $3,000 / Collab',
    audienceQualityScore: 90,
    authenticityScore: 92,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    demographics: {
      gender: { female: 62, male: 38 },
      ageGroups: [
        { label: '18-24', pct: 22 },
        { label: '25-34', pct: 58 },
        { label: '35-44', pct: 16 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 86 },
        { country: 'Malaysia', pct: 10 },
        { country: 'Other', pct: 4 },
      ],
      topInterests: ['Fine Dining', 'Date Night Guides', 'Weekend Getaways', 'Cocktail Pairings'],
    },
    mcpAudit: {
      decision: 'GOOD MATCH',
      matchReason: 'Exceptional save rate for restaurant lists. Highly converted audience demographic with above-average disposable income.',
      brandSafetyScore: 97,
      commercialIntentScore: 88,
      recommendationRank: 5,
    },
    recentProjects: [
      {
        id: 'proj-8',
        brand: 'Chope Singapore',
        brandLogo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=120&q=80',
        title: 'Top 10 Romantic Restaurants for Anniversaries',
        campaignType: 'Carousel Guide + Voucher Drop',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=600&q=80',
        impressions: '52.4K',
        reach: '44.1K',
        engagementRate: '5.1%',
        saves: 2840,
        shares: 1950,
        roiScore: 95,
        summary: 'High-performing reservation campaign resulting in 820 table bookings.',
      },
    ],
    recentPosts: [
      {
        id: 'post-8',
        type: 'Reel',
        caption: 'The most romantic garden restaurant in Dempsey where candlelight does all the work ✨',
        likes: '2,400',
        comments: '115',
        views: '38.0K',
        postedAt: '2 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-bryan-tan',
    name: 'Bryan Tan',
    handle: '@bryan_sg_fit',
    verified: false,
    platform: 'instagram',
    tag: 'Athletic Vibe',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 80,
    scoreBreakdown: {
      reach: 82,
      sentiment: 78,
      conversion: 80,
      algorithmConfidence: '80%',
    },
    category: 'Lifestyle SG',
    subCategories: ['Active Dating', 'Hyrox & Running Clubs', 'Athleisure'],
    location: 'Singapore',
    localAudiencePct: 76,
    followers: 120000,
    followersDisplay: '120K',
    engagementRate: 4.1,
    engagementRateDisplay: '4.1%',
    avgImpressions: 17200,
    avgImpressionsDisplay: '17.2K',
    avgEngagement: 820,
    avgEngagementDisplay: '820',
    timeOnTop: '6.2 hrs',
    statusText: 'Peak Time on Top: 6.2 hrs',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
    bio: 'Founder of East Coast Sunrise Run Club. Championing active dates, bouldering meetups, and fitness romance over late drinks.',
    detailedBio: 'Bryan has spearheaded Singapore’s fast-growing run club dating phenomenon, organizing Sunday 5K jogs followed by iced flat whites where over 200 singles connect weekly.',
    email: 'bryan@sgfitrun.com',
    agency: 'Independent',
    languages: ['English'],
    pricingRange: '$1,500 - $2,200 / Post',
    audienceQualityScore: 83,
    authenticityScore: 89,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    demographics: {
      gender: { female: 52, male: 48 },
      ageGroups: [
        { label: '18-24', pct: 30 },
        { label: '25-34', pct: 54 },
        { label: '35-44', pct: 12 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 76 },
        { country: 'Malaysia', pct: 14 },
        { country: 'Other', pct: 10 },
      ],
      topInterests: ['Running Clubs', 'Athleisure', 'Active Dating', 'Sports Nutrition'],
    },
    mcpAudit: {
      decision: 'GOOD MATCH',
      matchReason: 'Unique high-engagement community niche around active social wellness and singles run clubs in Singapore.',
      brandSafetyScore: 98,
      commercialIntentScore: 82,
      recommendationRank: 6,
    },
    recentProjects: [
      {
        id: 'proj-9',
        brand: 'Lululemon Singapore',
        brandLogo: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=120&q=80',
        title: 'Run & Coffee Singles Social Series',
        campaignType: 'Community Event + Reel',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=600&q=80',
        impressions: '38.0K',
        reach: '32.1K',
        engagementRate: '5.2%',
        saves: 1100,
        shares: 850,
        roiScore: 90,
        summary: 'Co-branded sunrise community run ending with complimentary matcha lattes and meet-and-greets.',
      },
    ],
    recentPosts: [
      {
        id: 'post-9',
        type: 'Reel',
        caption: 'Why Sunday morning run clubs became Singapore’s new speed dating scene 👟☕️',
        likes: '2,150',
        comments: '160',
        views: '31.2K',
        postedAt: '3 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1483721074577-8383e634336c?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-kevin-tech',
    name: 'Kevin Zhao',
    handle: '@kevinzhaotech',
    verified: true,
    platform: 'youtube',
    tag: 'TECH AUTHORITY',
    tagVariant: 'primary',
    shortlisted: false,
    score: 96,
    scoreBreakdown: { reach: 95, sentiment: 97, conversion: 93, algorithmConfidence: '96%' },
    category: 'Tech & Gadgets',
    subCategories: ['Smartphone Reviews', 'AI Tools & Productivity', 'Smart Home SG'],
    location: 'Singapore',
    localAudiencePct: 78,
    followers: 520000,
    followersDisplay: '520K',
    engagementRate: 6.4,
    engagementRateDisplay: '6.4%',
    avgImpressions: 89000,
    avgImpressionsDisplay: '89.0K',
    avgEngagement: 5700,
    avgEngagementDisplay: '5.7K',
    timeOnTop: '24 hrs',
    statusText: 'Peak Time on Top: 24 hrs',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    bio: 'Singapore hardware engineer turned tech creator. In-depth comparisons of flagships, laptops, and Apple vs Android ecosystems for Southeast Asia consumers.',
    detailedBio: 'Kevin is one of Southeast Asia’s most trusted voices in consumer electronics, reviewing flagship devices, smart home automation, and workspace tech with rigorous testing standards and high viewer retention.',
    email: 'partnerships@kevinzhaotech.com',
    agency: 'ByteWave Media',
    languages: ['English', 'Mandarin'],
    pricingRange: '$3,500 - $6,000 / Video',
    audienceQualityScore: 96,
    authenticityScore: 94,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    demographics: {
      gender: { female: 28, male: 72 },
      ageGroups: [
        { label: '18-24', pct: 24 },
        { label: '25-34', pct: 56 },
        { label: '35-44', pct: 16 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 78 },
        { country: 'Malaysia', pct: 12 },
        { country: 'Other', pct: 10 },
      ],
      topInterests: ['Consumer Electronics', 'AI Tools', 'Smart Home', 'PC Building'],
    },
    mcpAudit: {
      decision: 'TOP MATCH',
      matchReason: 'Unrivaled authority in gadget reviews with 96% buyer trust index across SG tech enthusiasts.',
      brandSafetyScore: 99,
      commercialIntentScore: 96,
      recommendationRank: 7,
    },
    recentProjects: [
      {
        id: 'proj-10',
        brand: 'Samsung Singapore',
        brandLogo: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=120&q=80',
        title: 'Galaxy S25 Ultra 30-Day Honest Review in SG',
        campaignType: 'Dedicated YouTube Video + IG Reel',
        date: 'Feb 2026',
        thumbnail: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
        impressions: '142K',
        reach: '118K',
        engagementRate: '7.1%',
        saves: 4200,
        shares: 3100,
        roiScore: 98,
        summary: 'Deep dive real-world camera shootout in Marina Bay and battery test on MRT rides.',
      },
    ],
    recentPosts: [
      {
        id: 'post-10',
        type: 'Video',
        caption: 'M4 MacBook Air vs Pro: The definitive guide for university & work in Singapore',
        likes: '7,400',
        comments: '420',
        views: '115K',
        postedAt: '2 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-michelle-eats',
    name: 'Michelle Koh',
    handle: '@michelle_sgfoodie',
    verified: true,
    platform: 'tiktok',
    tag: 'VIRAL FOODIE',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 93,
    scoreBreakdown: { reach: 96, sentiment: 91, conversion: 95, algorithmConfidence: '93%' },
    category: 'Food & Dining',
    subCategories: ['Hawker Gems', 'Fine Dining SG', 'Cafe Hopping'],
    location: 'Singapore',
    localAudiencePct: 92,
    followers: 430000,
    followersDisplay: '430K',
    engagementRate: 7.2,
    engagementRateDisplay: '7.2%',
    avgImpressions: 95000,
    avgImpressionsDisplay: '95.0K',
    avgEngagement: 6800,
    avgEngagementDisplay: '6.8K',
    timeOnTop: '16 hrs',
    statusText: 'Peak Time on Top: 16 hrs',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    bio: 'Full-time foodie uncovering hidden food gems from Old Airport Road to Michelin-starred omakase. 92% local SG audience looking for what to eat this weekend!',
    detailedBio: 'Michelle is Singapore’s go-to dining curator. Her snappy, authentic TikTok food tours regularly cause 2-hour queues at featured eateries across the island.',
    email: 'collabs@michellefoodie.sg',
    agency: 'Flavor Collective',
    languages: ['English', 'Mandarin', 'Hokkien'],
    pricingRange: '$2,400 - $3,800 / Post',
    audienceQualityScore: 93,
    authenticityScore: 92,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    demographics: {
      gender: { female: 65, male: 35 },
      ageGroups: [
        { label: '18-24', pct: 32 },
        { label: '25-34', pct: 52 },
        { label: '35-44', pct: 12 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 92 },
        { country: 'Malaysia', pct: 5 },
        { country: 'Other', pct: 3 },
      ],
      topInterests: ['Food & Dining', 'Hawker Culture', 'Weekend Brunches', 'Cocktail Bars'],
    },
    mcpAudit: {
      decision: 'STRONG FIT',
      matchReason: 'Unmatched 92% local Singapore footprint. Immediate footfall driver for F&B establishments.',
      brandSafetyScore: 99,
      commercialIntentScore: 94,
      recommendationRank: 8,
    },
    recentProjects: [
      {
        id: 'proj-11',
        brand: 'GrabFood SG',
        brandLogo: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=120&q=80',
        title: 'Hidden Gem Supper Trails Delivery Campaign',
        campaignType: 'TikTok Video Series',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
        impressions: '180K',
        reach: '150K',
        engagementRate: '8.4%',
        saves: 8900,
        shares: 6200,
        roiScore: 97,
        summary: 'Showcasing midnight supper eats available exclusively on GrabFood Dine-in and Delivery.',
      },
    ],
    recentPosts: [
      {
        id: 'post-11',
        type: 'Reel',
        caption: '5 hawker stalls in Chinatown that tourists do NOT know about yet 🔥🤤',
        likes: '14,200',
        comments: '380',
        views: '240K',
        postedAt: '1 day ago',
        thumbnail: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-elena-style',
    name: 'Elena Chua',
    handle: '@elenachua_style',
    verified: true,
    platform: 'instagram',
    tag: 'FASHION ICON',
    tagVariant: 'tertiary',
    shortlisted: false,
    score: 95,
    scoreBreakdown: { reach: 93, sentiment: 96, conversion: 94, algorithmConfidence: '95%' },
    category: 'Fashion & Luxury',
    subCategories: ['Capsule Wardrobes', 'Luxury Hauls', 'Office Chic SG'],
    location: 'Singapore',
    localAudiencePct: 82,
    followers: 340000,
    followersDisplay: '340K',
    engagementRate: 5.8,
    engagementRateDisplay: '5.8%',
    avgImpressions: 58000,
    avgImpressionsDisplay: '58.0K',
    avgEngagement: 3400,
    avgEngagementDisplay: '3.4K',
    timeOnTop: '20 hrs',
    statusText: 'Peak Time on Top: 20 hrs',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
    bio: 'Curating timeless, climate-smart style for the modern Southeast Asian woman. Featured in Harper’s BAZAAR SG and Vogue Singapore.',
    detailedBio: 'Elena specializes in luxury-accessible fashion styling, capsule wardrobe curation, and premium lifestyle aesthetics with an impeccably engaged female executive demographic.',
    email: 'contact@elenachua.com',
    agency: 'Avenue Talent PR',
    languages: ['English', 'French'],
    pricingRange: '$3,200 - $5,000 / Collab',
    audienceQualityScore: 97,
    authenticityScore: 93,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    demographics: {
      gender: { female: 84, male: 16 },
      ageGroups: [
        { label: '18-24', pct: 20 },
        { label: '25-34', pct: 60 },
        { label: '35-44', pct: 16 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 82 },
        { country: 'Malaysia', pct: 10 },
        { country: 'Other', pct: 8 },
      ],
      topInterests: ['Luxury Fashion', 'Designer Handbags', 'Fine Jewelry', 'High Tea'],
    },
    mcpAudit: {
      decision: 'TOP MATCH',
      matchReason: 'Premium corporate executive & high-net-worth female demographic alignment across CBD Singapore.',
      brandSafetyScore: 100,
      commercialIntentScore: 95,
      recommendationRank: 9,
    },
    recentProjects: [
      {
        id: 'proj-12',
        brand: 'Dior SG',
        brandLogo: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=120&q=80',
        title: 'Lady Dior Spring/Summer Pop-Up Exhibition',
        campaignType: 'IG Feed Carousels & Reels',
        date: 'Feb 2026',
        thumbnail: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80',
        impressions: '72K',
        reach: '60K',
        engagementRate: '6.2%',
        saves: 3400,
        shares: 1200,
        roiScore: 98,
        summary: 'Styling the new Lady D-Joy bag with tailored workwear suited for Singapore humidity.',
      },
    ],
    recentPosts: [
      {
        id: 'post-12',
        type: 'Carousel',
        caption: '5 investment pieces every 30-something woman in Singapore should own for endless versatility 🕊️',
        likes: '6,800',
        comments: '190',
        views: '62K',
        postedAt: '2 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-darren-finance',
    name: 'Darren Lim',
    handle: '@darren_wealth_sg',
    verified: true,
    platform: 'youtube',
    tag: 'FINANCE GURU',
    tagVariant: 'primary',
    shortlisted: false,
    score: 92,
    scoreBreakdown: { reach: 90, sentiment: 94, conversion: 93, algorithmConfidence: '92%' },
    category: 'Finance & Wealth',
    subCategories: ['CPF & SRS Optimization', 'BTO Investing', 'Robo-advisors SG'],
    location: 'Singapore',
    localAudiencePct: 88,
    followers: 290000,
    followersDisplay: '290K',
    engagementRate: 5.1,
    engagementRateDisplay: '5.1%',
    avgImpressions: 48000,
    avgImpressionsDisplay: '48.0K',
    avgEngagement: 2500,
    avgEngagementDisplay: '2.5K',
    timeOnTop: '12 hrs',
    statusText: 'Peak Time on Top: 12 hrs',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=1200&q=80',
    bio: 'Demystifying Singapore personal finance, CPF hacks, property purchasing rules, and index investing for young professionals.',
    detailedBio: 'Darren brings clarity to Singapore tax, housing policies, and investment vehicles with clear spreadsheets, visual graphs, and actionable guidance.',
    email: 'darren@financesg.media',
    agency: 'Ascent Talent',
    languages: ['English', 'Mandarin'],
    pricingRange: '$2,800 - $4,500 / Video',
    audienceQualityScore: 95,
    authenticityScore: 96,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    demographics: {
      gender: { female: 38, male: 62 },
      ageGroups: [
        { label: '18-24', pct: 18 },
        { label: '25-34', pct: 64 },
        { label: '35-44', pct: 14 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 88 },
        { country: 'Malaysia', pct: 8 },
        { country: 'Other', pct: 4 },
      ],
      topInterests: ['Personal Finance', 'BTO Housing', 'CPF Investments', 'High Yield Savings'],
    },
    mcpAudit: {
      decision: 'STRONG FIT',
      matchReason: 'Exceptional trust factor for fintech, wealth management, insurance, and banking integrations.',
      brandSafetyScore: 100,
      commercialIntentScore: 97,
      recommendationRank: 10,
    },
    recentProjects: [
      {
        id: 'proj-13',
        brand: 'Endowus SG',
        brandLogo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&q=80',
        title: 'How to Maximize Your CPF OA Returns Safely in 2026',
        campaignType: 'YouTube Deep Dive & Case Study',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=600&q=80',
        impressions: '84K',
        reach: '71K',
        engagementRate: '5.8%',
        saves: 4900,
        shares: 3100,
        roiScore: 97,
        summary: 'Step-by-step portfolio walkthrough comparing cash vs CPF investment options.',
      },
    ],
    recentPosts: [
      {
        id: 'post-13',
        type: 'Video',
        caption: 'The hidden trap in 30-year Singapore mortgage rates nobody is talking about 📉',
        likes: '5,200',
        comments: '310',
        views: '88K',
        postedAt: '3 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-farah-travel',
    name: 'Farah Rahim',
    handle: '@farah_travel_my',
    verified: true,
    platform: 'instagram',
    tag: 'REGIONAL CREATOR',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 89,
    scoreBreakdown: { reach: 92, sentiment: 93, conversion: 87, algorithmConfidence: '89%' },
    category: 'Travel & Escapes',
    subCategories: ['Southeast Asia Roadtrips', 'Boutique Resorts', 'Island Hopping'],
    location: 'Malaysia',
    localAudiencePct: 62,
    followers: 480000,
    followersDisplay: '480K',
    engagementRate: 6.0,
    engagementRateDisplay: '6.0%',
    avgImpressions: 74000,
    avgImpressionsDisplay: '74.0K',
    avgEngagement: 4500,
    avgEngagementDisplay: '4.5K',
    timeOnTop: '15 hrs',
    statusText: 'Peak Time on Top: 15 hrs',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    bio: 'Kuala Lumpur & Singapore travel creator exploring hidden islands, eco-retreats, and scenic weekend road trips across Southeast Asia.',
    detailedBio: 'Farah captures the wanderlust of cross-border travelers between Singapore, Malaysia, and Bali with stunning cinematic reels and practical itineraries.',
    email: 'booking@farahtravel.com',
    agency: 'Nomad Digital',
    languages: ['English', 'Malay'],
    pricingRange: '$2,600 - $4,200 / Series',
    audienceQualityScore: 91,
    authenticityScore: 92,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    demographics: {
      gender: { female: 58, male: 42 },
      ageGroups: [
        { label: '18-24', pct: 26 },
        { label: '25-34', pct: 58 },
        { label: '35-44', pct: 12 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Malaysia', pct: 52 },
        { country: 'Singapore', pct: 36 },
        { country: 'Other', pct: 12 },
      ],
      topInterests: ['Weekend Getaways', 'Beach Resorts', 'Aviation & Hotels', 'Nature Trails'],
    },
    mcpAudit: {
      decision: 'GOOD MATCH',
      matchReason: 'Cross-border regional reach connecting Singapore vacationers with Malaysia and regional tourism.',
      brandSafetyScore: 99,
      commercialIntentScore: 89,
      recommendationRank: 11,
    },
    recentProjects: [
      {
        id: 'proj-14',
        brand: 'Singapore Airlines',
        brandLogo: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=120&q=80',
        title: 'Hidden Gem Islands Just 2 Hours From Changi',
        campaignType: 'Sponsored Reel Series',
        date: 'Dec 2025',
        thumbnail: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=600&q=80',
        impressions: '110K',
        reach: '95K',
        engagementRate: '6.7%',
        saves: 5400,
        shares: 4100,
        roiScore: 95,
        summary: '48-hour itinerary guide for quick weekend escapes from Singapore.',
      },
    ],
    recentPosts: [
      {
        id: 'post-14',
        type: 'Reel',
        caption: 'The most tranquil cliffside villa in Langkawi you won’t want to leave 🌊✨',
        likes: '8,900',
        comments: '240',
        views: '124K',
        postedAt: '4 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-sean-comedy',
    name: 'Sean Tan',
    handle: '@seantastic_sg',
    verified: true,
    platform: 'tiktok',
    tag: 'GEN Z VIRAL',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 91,
    scoreBreakdown: { reach: 98, sentiment: 88, conversion: 89, algorithmConfidence: '91%' },
    category: 'Comedy & Entertainment',
    subCategories: ['Singlish Parodies', 'Corporate SG Humor', 'MRT Relatability'],
    location: 'Singapore',
    localAudiencePct: 89,
    followers: 610000,
    followersDisplay: '610K',
    engagementRate: 8.9,
    engagementRateDisplay: '8.9%',
    avgImpressions: 160000,
    avgImpressionsDisplay: '160K',
    avgEngagement: 14000,
    avgEngagementDisplay: '14.0K',
    timeOnTop: '22 hrs',
    statusText: 'Peak Time on Top: 22 hrs',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    bio: 'Making Singapore laugh at everyday corporate trauma, MRT breakdowns, and relatable Gen Z struggles. 8.9% engagement rate!',
    detailedBio: 'Sean is one of Singapore’s fastest-growing sketch comedians, crafting instantly viral skits about Raffles Place office culture, national service memories, and family group chats.',
    email: 'sean@seantastic.sg',
    agency: 'Laugh Factory Asia',
    languages: ['English', 'Singlish', 'Mandarin'],
    pricingRange: '$2,800 - $4,800 / Skit',
    audienceQualityScore: 92,
    authenticityScore: 97,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    demographics: {
      gender: { female: 50, male: 50 },
      ageGroups: [
        { label: '18-24', pct: 45 },
        { label: '25-34', pct: 45 },
        { label: '35-44', pct: 8 },
        { label: '45+', pct: 2 },
      ],
      geography: [
        { country: 'Singapore', pct: 89 },
        { country: 'Malaysia', pct: 8 },
        { country: 'Other', pct: 3 },
      ],
      topInterests: ['Comedy & Memes', 'Local Pop Culture', 'Casual Dining', 'Mobile Gaming'],
    },
    mcpAudit: {
      decision: 'STRONG FIT',
      matchReason: 'Top viral reach and shareability across Gen Z & millennial Singapore demographic.',
      brandSafetyScore: 96,
      commercialIntentScore: 86,
      recommendationRank: 12,
    },
    recentProjects: [
      {
        id: 'proj-15',
        brand: 'Circles.Life SG',
        brandLogo: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=120&q=80',
        title: 'Types of People on the EW Line MRT Skit',
        campaignType: 'Branded TikTok Comedy Skit',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=600&q=80',
        impressions: '320K',
        reach: '280K',
        engagementRate: '9.4%',
        saves: 12400,
        shares: 18200,
        roiScore: 99,
        summary: 'Hilarious branded integration highlighting unlimited mobile data during peak hour commute.',
      },
    ],
    recentPosts: [
      {
        id: 'post-15',
        type: 'Reel',
        caption: 'When your boss says "let’s have a quick sync" at 5:58 PM on Friday 💀😭',
        likes: '28,400',
        comments: '720',
        views: '410K',
        postedAt: '1 day ago',
        thumbnail: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-nadia-fitness',
    name: 'Nadia Iskandar',
    handle: '@nadiaruns_sg',
    verified: true,
    platform: 'instagram',
    tag: 'FITNESS COACH',
    tagVariant: 'primary',
    shortlisted: false,
    score: 93,
    scoreBreakdown: { reach: 91, sentiment: 97, conversion: 91, algorithmConfidence: '93%' },
    category: 'Fitness & Wellness',
    subCategories: ['Marathon Training', 'Hyrox SG', 'Plant-based Nutrition'],
    location: 'Singapore',
    localAudiencePct: 84,
    followers: 185000,
    followersDisplay: '185K',
    engagementRate: 6.8,
    engagementRateDisplay: '6.8%',
    avgImpressions: 42000,
    avgImpressionsDisplay: '42.0K',
    avgEngagement: 2800,
    avgEngagementDisplay: '2.8K',
    timeOnTop: '18 hrs',
    statusText: 'Peak Time on Top: 18 hrs',
    avatar: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=1200&q=80',
    bio: 'Marathoner, HYROX competitor & fitness coach in Singapore. Empowering busy corporate warriors to build sustainable strength and recovery habits.',
    detailedBio: 'Nadia is an inspiring figure in Singapore’s thriving endurance running and HYROX fitness communities. Her training logs and recovery advice enjoy near-perfect engagement and authenticity ratings.',
    email: 'nadia@fitcoachsg.com',
    agency: 'ProActive Sports PR',
    languages: ['English', 'Malay'],
    pricingRange: '$1,900 - $3,200 / Reel',
    audienceQualityScore: 97,
    authenticityScore: 98,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    demographics: {
      gender: { female: 62, male: 38 },
      ageGroups: [
        { label: '18-24', pct: 22 },
        { label: '25-34', pct: 58 },
        { label: '35-44', pct: 16 },
        { label: '45+', pct: 4 },
      ],
      geography: [
        { country: 'Singapore', pct: 84 },
        { country: 'Malaysia', pct: 10 },
        { country: 'Other', pct: 6 },
      ],
      topInterests: ['Endurance Running', 'Pilates & Strength', 'Recovery Tech', 'Athleisure'],
    },
    mcpAudit: {
      decision: 'STRONG FIT',
      matchReason: 'Unmatched authenticity in wellness and fitness with high conversion on activewear and nutrition brands.',
      brandSafetyScore: 100,
      commercialIntentScore: 91,
      recommendationRank: 13,
    },
    recentProjects: [
      {
        id: 'proj-16',
        brand: 'Garmin SG',
        brandLogo: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=120&q=80',
        title: 'Marathon Training Pacing with Forerunner 965',
        campaignType: 'Product Ambassador Reel Series',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1510519138161-58474ebf899a?auto=format&fit=crop&w=600&q=80',
        impressions: '64K',
        reach: '52K',
        engagementRate: '7.2%',
        saves: 3200,
        shares: 1900,
        roiScore: 96,
        summary: 'Heart-rate zone training breakdown during a 21km East Coast Park long run.',
      },
    ],
    recentPosts: [
      {
        id: 'post-16',
        type: 'Reel',
        caption: '5 mobility exercises every runner should do after 10K to protect their knees in SG heat 🏃‍♀️🧘‍♀️',
        likes: '4,800',
        comments: '145',
        views: '54K',
        postedAt: '2 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-chloe-beauty',
    name: 'Chloe Teo',
    handle: '@chloeteo_glow',
    verified: true,
    platform: 'tiktok',
    tag: 'DERM APPROVED',
    tagVariant: 'tertiary',
    shortlisted: false,
    score: 94,
    scoreBreakdown: { reach: 93, sentiment: 97, conversion: 92, algorithmConfidence: '94%' },
    category: 'Beauty & Skincare',
    subCategories: ['Glass Skin SG', 'Acne Journey', 'Ingredient Science'],
    location: 'Singapore',
    localAudiencePct: 86,
    followers: 260000,
    followersDisplay: '260K',
    engagementRate: 7.5,
    engagementRateDisplay: '7.5%',
    avgImpressions: 62000,
    avgImpressionsDisplay: '62.0K',
    avgEngagement: 4600,
    avgEngagementDisplay: '4.6K',
    timeOnTop: '19 hrs',
    statusText: 'Peak Time on Top: 19 hrs',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
    bio: 'Biochemistry grad sharing science-backed skincare reviews for humid climates. No filtered skin, only real results.',
    detailedBio: 'Chloe tests serums, sunscreens, and dermatological formulas against Singapore’s high humidity and UV indices, building enormous credibility among consumers tired of beauty gimmicks.',
    email: 'chloe@glowcollective.sg',
    agency: 'Lumen Talent Collective',
    languages: ['English', 'Mandarin'],
    pricingRange: '$2,200 - $3,600 / Video',
    audienceQualityScore: 98,
    authenticityScore: 99,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    demographics: {
      gender: { female: 89, male: 11 },
      ageGroups: [
        { label: '18-24', pct: 36 },
        { label: '25-34', pct: 52 },
        { label: '35-44', pct: 10 },
        { label: '45+', pct: 2 },
      ],
      geography: [
        { country: 'Singapore', pct: 86 },
        { country: 'Malaysia', pct: 8 },
        { country: 'Other', pct: 6 },
      ],
      topInterests: ['K-Beauty', 'Sunscreens for Humidity', 'Barrier Repair', 'Clinical Skincare'],
    },
    mcpAudit: {
      decision: 'TOP MATCH',
      matchReason: 'Scientific ingredient analysis and raw camera quality yield 98% trust rating in skincare integrations.',
      brandSafetyScore: 100,
      commercialIntentScore: 95,
      recommendationRank: 14,
    },
    recentProjects: [
      {
        id: 'proj-17',
        brand: 'La Roche-Posay SG',
        brandLogo: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=120&q=80',
        title: 'UV Camera Sunscreen Breakdown Under Midday SG Sun',
        campaignType: 'TikTok Educational Demo',
        date: 'Feb 2026',
        thumbnail: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=600&q=80',
        impressions: '128K',
        reach: '105K',
        engagementRate: '8.1%',
        saves: 7200,
        shares: 4800,
        roiScore: 99,
        summary: 'Direct UV camera visualization showing oil control and water resistance after 6 hours outdoors.',
      },
    ],
    recentPosts: [
      {
        id: 'post-17',
        type: 'Video',
        caption: 'The 3 skincare ingredients you should NEVER mix if you sweat easily in Singapore 💦🚫',
        likes: '11,200',
        comments: '290',
        views: '168K',
        postedAt: '1 day ago',
        thumbnail: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'kol-ryan-gaming',
    name: 'Ryan "Kitsune" Goh',
    handle: '@kitsunegoh_sg',
    verified: true,
    platform: 'youtube',
    tag: 'ESPORTS CREATOR',
    tagVariant: 'secondary',
    shortlisted: false,
    score: 90,
    scoreBreakdown: { reach: 95, sentiment: 89, conversion: 86, algorithmConfidence: '90%' },
    category: 'Gaming & Esports',
    subCategories: ['Valorant SEA', 'Custom Keyboards', 'Streaming Setups'],
    location: 'Singapore',
    localAudiencePct: 75,
    followers: 390000,
    followersDisplay: '390K',
    engagementRate: 7.0,
    engagementRateDisplay: '7.0%',
    avgImpressions: 80000,
    avgImpressionsDisplay: '80.0K',
    avgEngagement: 5600,
    avgEngagementDisplay: '5.6K',
    timeOnTop: '14 hrs',
    statusText: 'Peak Time on Top: 14 hrs',
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    bio: 'Ex-competitive Valorant player streaming tactical FPS, custom mechanical keyboards, and gaming battlestation builds in Singapore.',
    detailedBio: 'Ryan is a premier gaming and streaming creator in Singapore and Malaysia, delivering entertaining gameplay guides, hardware testing, and dynamic esports commentary.',
    email: 'partnerships@kitsunegoh.gg',
    agency: 'Respawn Media',
    languages: ['English', 'Mandarin'],
    pricingRange: '$2,500 - $4,200 / Video',
    audienceQualityScore: 92,
    authenticityScore: 95,
    lastSyncedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    demographics: {
      gender: { female: 20, male: 80 },
      ageGroups: [
        { label: '18-24', pct: 54 },
        { label: '25-34', pct: 38 },
        { label: '35-44', pct: 6 },
        { label: '45+', pct: 2 },
      ],
      geography: [
        { country: 'Singapore', pct: 75 },
        { country: 'Malaysia', pct: 15 },
        { country: 'Other', pct: 10 },
      ],
      topInterests: ['Esports', 'Mechanical Keyboards', 'Gaming Mice', 'Anime & Manga'],
    },
    mcpAudit: {
      decision: 'GOOD MATCH',
      matchReason: 'High male Gen Z demographic concentration with strong enthusiasm for hardware, snacks, and tech.',
      brandSafetyScore: 97,
      commercialIntentScore: 88,
      recommendationRank: 15,
    },
    recentProjects: [
      {
        id: 'proj-18',
        brand: 'Razer Singapore',
        brandLogo: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=120&q=80',
        title: 'Building the Ultimate Stealth Desk Setup in a 4-Room BTO',
        campaignType: 'YouTube Dedicated Setup Tour',
        date: 'Jan 2026',
        thumbnail: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=600&q=80',
        impressions: '98K',
        reach: '82K',
        engagementRate: '7.8%',
        saves: 4500,
        shares: 3100,
        roiScore: 95,
        summary: 'Desk aesthetic makeover incorporating cable management and ambient smart lighting.',
      },
    ],
    recentPosts: [
      {
        id: 'post-18',
        type: 'Video',
        caption: 'The $40 magnetic switch keyboard that pro players in SEA are switching to ⌨️🎯',
        likes: '7,900',
        comments: '360',
        views: '112K',
        postedAt: '2 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
];
